'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class IHT45_RE
    
    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''lblLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLine As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnOV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOV As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnTR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTR As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnPI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPI As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnAL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAL As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnPrint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrint As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblPartNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPartNumber As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtPart_Nr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPart_Nr As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblPart_Type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPart_Type As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtPart_Type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPart_Type As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtRecipeDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRecipeDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chbHist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chbHist As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''tbxRecipeDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxRecipeDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''Calendar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Calendar1 As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''ddlRecipeDates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRecipeDates As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tblHarden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblHarden As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''lblDate0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDate0 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDateS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateS As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbxH1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxH1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxOH1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxOH1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxH2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxH2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxOH2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxOH2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxH3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxH3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxOH3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxOH3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxH4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxH4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxOH4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxOH4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxH5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxH5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxOH5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxOH5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxH6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxH6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxOH6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxOH6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxH7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxH7 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxOH7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxOH7 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxH8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxH8 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxOH8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxOH8 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxH9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxH9 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxOH9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxOH9 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxH10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxH10 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxOH10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxOH10 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxH11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxH11 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxOH11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxOH11 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxH12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxH12 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxOH12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxOH12 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxH13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxH13 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxOH13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxOH13 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxH14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxH14 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxOH14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxOH14 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxH15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxH15 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxOH15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxOH15 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxH16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxH16 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxOH16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxOH16 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxH17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxH17 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxOH17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxOH17 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxH18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxH18 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxOH18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxOH18 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxH19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxH19 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxOH19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxOH19 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxH20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxH20 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxOH20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxOH20 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxH21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxH21 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxOH21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxOH21 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxH22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxH22 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxOH22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxOH22 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tblTemper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblTemper As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''lblDate1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDate1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDateST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateST As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbxT1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxT1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxOT1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxOT1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxT2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxT2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxOT2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxOT2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxT3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxT3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxOT3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxOT3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxT4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxT4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxOT4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxOT4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxT5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxT5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxOT5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxOT5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxT6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxT6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxOT6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxOT6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxT7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxT7 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxOT7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxOT7 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''SqlIHTRecipe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlIHTRecipe As Global.System.Web.UI.WebControls.SqlDataSource
End Class
